### PR TITLE
Correct duplication/names of a few recent pods

### PR DESCRIPTION
**Pull request by mhuusko5**
Would like to remove this duplicate spec (with wrong name), hoping it won't be too much trouble/do any (user) damage as it's only about an hour old.

### CODE REVIEW

**Comment by mhuusko5** [comment]
Also would like to correct the names of two other specs, both also quite small/recent. Know it's not best practice – if these were more significant and/or used, would go the deprecation route (also if the Cocoapods deprecation mechanism stopped deprecated pods from showing up on the cocoapods.org).

**Comment by mhuusko5** [comment]
Any chance on acting on this sooner than later? Especially with regards to NSPointerArray-M5Additions (only a day old now), would be good to make these changes before people start using it/them.

**Comment by Keithbsmiley** [comment]
If you remove the renames from the other pod I'll merge these removals.

**Comment by Keithbsmiley** [comment]
Renaming that, since it isn't renamed in trunk is going to break things, which is pretty annoying.

**Comment by Keithbsmiley** [comment]
You should push `UILabel+M5FillFrame` via trunk instead, and then submit a PR to mark `UILabel-M5FillFrame` as `deprecated_in_favor_of` the new one.

**Comment by mhuusko5** [comment]
Okay, now it's only the removal of NSPointerArray-M5Additions. Thanks for the help!

Out of curiosity, re: deprecated_in_favor_of, doing so currently only shows a warning when you view a pod on cocoapods.org... but that pod still shows up, and looks normal, in the search – is that the desired functionality? Because it doesn't seem entirely sufficient... if you're marking a pod as deprecated, its because its not supported at all anymore.

In this case, UILabel-M5FillFrame is basically a fluke and won't be supported at all... but it is destined to exist forever unless it is actually removed (which you said would screw up interaction with trunk).

**Comment by Keithbsmiley** [comment]
You can submit a PR to remove it entirely. And then you can push the new versions with trunk if you haven't already.

**Pull request merged**
