### PR TITLE
[Add] DJScrollView version 1.0.0

### PR DESCRIPTION
**Pull request by yangfeng666**

### CODE REVIEW

**Comment by keith** [comment]
Please stop opening pull requests and read my previous comments.

**Comment by linlin1314** [comment]
真弄不明白，我是照着最新提交的修改的，不知道具体哪儿错了

**Comment by squarefrog** [comment]
You have to submit pods using [Trunk](https://guides.cocoapods.org/making/getting-setup-with-trunk.html). You no longer submit using Pull Requests.

**Comment by bawn** [comment]
@linlin1314 现在已经改成Trunk的方式提交了，请看这个http://yulingtianxia.com/blog/2014/05/26/publish-your-pods-on-cocoapods-with-trunk/

**Pull request closed without merging**
