### PR TITLE
delete test pod spec

### PR DESCRIPTION
**Pull request by ghost**
no use for these code

### CODE REVIEW

**Comment by xiaoxiao1987** [comment]
please delete it

**Comment by xiaoxiao1987** [comment]
@CocoaPodsBot please delete it

**Comment by segiddins** [comment]
@xiaoxiao1987 you should use `pod trunk deleted` which is a command included in the 1.0 release candidate.

**Comment by xiaoxiao1987** [comment]
@segiddins Thank you for your reply! But i had try to delete that pod under version 1.0.0.rc.1, and i got this error :  [!] No pod found with the specified name.  So i don't know how to due with it. Please help me delete it .Thank you very much !

**Comment by segiddins** [comment]
did you run `pod trunk delete FirstCocoaPods` ?

**Comment by xiaoxiao1987** [comment]
@segiddins yes, and deprecate is no use too.....

**Pull request closed without merging**
