### PR TITLE
Removed the TestmunkCalabash, since it is no longer being maintained

### PR DESCRIPTION
**Pull request by mashhoodr**
We are now using the Calabash Pod, this variant is no longer being maintained so it needs to be removed.

### CODE REVIEW

**Comment by segiddins** [comment]
We recommend deprecating the pod, instead of deleting it completely.

**Comment by mashhoodr** [comment]
@segiddins Thanks, already deprecated. It would be nice if it can be removed as well. Otherwise this PR can be closed.

**Comment by segiddins** [comment]
Those podspecs don't seem to be deprecated to me?

**Comment by mashhoodr** [comment]
I added a new version with the deprecation. I tried updating the old one but it didnt let me.

**Comment by keith** [comment]
@mashhoodr you can submit a PR to deprecate these.

**Pull request closed without merging**
