### PR TITLE
Fix license in podspec of AppsFlyer-SDK. It is not a MIT library

### PR DESCRIPTION
**Pull request by dcordero**
Fix license in podspec of AppsFlyer-SDK. It is not a MIT library

### CODE REVIEW

**Comment by orta** [comment]
The type should be "Proprietary", copyright isn't a form of license - other than that, should be fine to merge.

**Comment by dcordero** [comment]
Fixed :white_check_mark: 

Thanks @orta

**Comment by weibel** [comment]
pod install says
```[!] Unable to read the license file `[...]/Pods/AppsFlyer-SDK/LICENSE` for the spec `AppsFlyer-SDK (2.5.3.14)````

**Comment by dcordero** [comment]
Indeed @weibel . That was the reason of my fix here for the version 2.5.3.11. But the owner of the pod didn't take the fix is publishing the new version with the same error again and again

**Comment by weibel** [comment]
Is it appsflyer.com themselves who owns the pod? I'll open a ticket on their end. However it does not look like they officially support Cocoapods

**Comment by dcordero** [comment]
I sent a again a PR with the fix https://github.com/CocoaPods/Specs/pull/13058

**Pull request merged**
