### PR TITLE
removed unwanted spec versions

### PR DESCRIPTION
**Pull request by kraetos10**
Hi, 

I'm a developer at Donky networks ltd. This is out initial cocoa pods release and while getting up to speed with the procedure we created a few unwanted versions. If we can get this merged back in we can push our release versions back in. Thanks

### CODE REVIEW

**Comment by squarefrog** [comment]
It is generally preferred that you mark the old ones as [`deprecated_in_favor_of`](http://guides.cocoapods.org/syntax/podspec.html#deprecated_in_favor_of) the new one.

I highly recommend you read the [subspec guide](http://guides.cocoapods.org/syntax/podspec.html#subspec), as a cursory look through your Specs make it seem like an ideal candidate.

If you intend to replace these various Specs with a single Spec and Subspecs then it would definitely be appropriate to remove the old version.

**Comment by chriswatson00** [comment]
Hi 
Thanks for the reply. Deprecated seems interesting. I also need to make all specs v 1.0.0. If there's a higher version already in there would this still work ?

Regards,

Chris Watson

**Comment by squarefrog** [comment]
No, unfortunately, the higher spec number will supercede the new Spec. In this case we will make an exception and merge this pull request.

In future, while developing a Pod you may find having a [Private Spec Repo](http://guides.cocoapods.org/making/private-cocoapods.html) useful.

**Comment by chriswatson00** [comment]
Yes thank you very much. Saved my life. I was new to it and made a bit of noise around versions. 

Regards,

Chris Watson

**Comment by chriswatson00** [comment]
HI, 

Sorry to bother you again, it seems the version on cocoapods.org for these pod specs still reflects the old ones and as such the links to the pod spec return 404. Is this something that I need to rectify ? 

Thanks 


Regards, 

Chris Watson

**Comment by orta** [comment]
@chriswatson00 the pods db is built to be write-once, read often - if we mark your pods as deleted you cannot easily bring them back when you decide to release. 

If you're planning on officially releasing soon, I would recommend we don't mark them as deleted.

**Pull request merged**
