### PR TITLE
Change summaries for Fabric CocoaPods

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by segiddins** [comment]
\c @orta @keith

**Comment by orta** [comment]
These old ones are from unofficial sources. This is a shame, but people will end up being forced updated I think, unless they are extremely specific in their version on the Podfile. Other than that looks good :+1:

**Comment by ohwutup** [comment]
thanks @orta and @segiddins !

**Comment by bakemecookies** [comment]
apologies if this isn't the right/best place for this, but is there any reason why https://cocoapods.org/?q=fabric doesn't reflect the fact that 1.3.0-1.3.2 have been deleted and that 1.2.8 is the latest version?  (also mentioned a couple weeks ago by @ohwutup in the now-locked #13313)

**Comment by orta** [comment]
There is a separate database for trunk + APIs which is essentially read-only, removing the Specs doesn't remove them from that. We're still trying to figure out the [right way](https://github.com/CocoaPods/trunk.cocoapods.org/issues/46#issuecomment-123651100) to support the removal of a spec version from that database.

**Pull request merged**
