### PR TITLE
[Add] 1PasswordExtension 1.1.2

### PR DESCRIPTION
**Pull request by radazzouz**
[FIXED] Fixed issue that was causing the 1Password 5.3 Beta Extension to crash when attempting to fill into UIWebViews.

### CODE REVIEW

**Comment by squarefrog** [comment]
@tapi is the owner of this pod, try and contact him to push the update through trunk. I'll let @Keithbsmiley decide whether to close this issue or not.

--- 

We have just launched 'Trunk', which is the new way for you to submit your Pods. For more information on this have a read through the post at http://blog.cocoapods.org/CocoaPods-Trunk/ If you have previously had your Pod merged into the master repository, please ensure you claim your Pod http://blog.cocoapods.org/Claim-Your-Pods/

**Comment by tapi** [comment]
Sorry guys, been busy and I missed this. Should be good to go now. @radazzouz we should definitely set one of you up with push access to the trunk

**Comment by radazzouz** [comment]
Thanks guys! Please let me know what do I need to do to push gain access to the trunk.

**Comment by squarefrog** [comment]
@tapi to add @radazzouz as an owner do the following

    $ pod trunk add-owner 1PasswordExtension rad@email-address.com

You'll need to use the email that @radazzouz has [registered with trunk](http://guides.cocoapods.org/making/getting-setup-with-trunk.html#getting-started).

I'll leave it up to you guys how to contact each other and figure out each others emails. I'll close this now and you can push yourself using trunk. Shout me if anything is unclear.

**Comment by tapi** [comment]
@squarefrog 👍

**Comment by tapi** [comment]
@squarefrog Are you a Cocoapods contributor? It looks like there is an issue with trunk. the pod spec says 1.1.2 but when you look it up on search its coming up as 1.1

**Comment by squarefrog** [comment]
I am yes.

It's showing up [on cocoapods.org](http://cocoapods.org/?q=1passwordext), so all you need to do is run

    $ pod repo update

Then it'll show up.

**Comment by tapi** [comment]
```pod repo update``` did the trick locally. 
If you mouse over the clipboard on cocoapods.org its still giving the pod file line for 1.1

**Comment by squarefrog** [comment]
*Not quite* - 

    pod '1PasswordExtension', '~> 1.1'

means any 1PasswordExtension pod equal to or greater than 1.1, but less than 1.2. Which 1.1.2, falls under.

**Comment by tapi** [comment]
I know the ~> syntax will use the latest compatible version. 
It was just a source of confusion on another thread so we weren't sure if there was an issue that cropped up somewhere. Thx.

**Pull request closed without merging**
