### PR TITLE
Deprecated the spec and ask the pod deletion.

### PR DESCRIPTION
**Pull request by King-Wizard**
Deprecated the specs and ask the pod deletion, because I inadvertently pushed these specs.

### CODE REVIEW

**Comment by keith** [comment]
If you pushed all of these very recently we can delete them. How recent are they?

**Comment by King-Wizard** [comment]
I pushed them few hours ago.

**Comment by keith** [comment]
You can remove them in this PR

**Comment by King-Wizard** [comment]
Ok I am going to do that in few minutes.

**Comment by King-Wizard** [comment]
Done.

It is the first time that I do that, please tell me what is going to happen right now, are you going to merge my PR and delete these podspec from the Trunk database?

Thank you in advance for your answer.

**Comment by keith** [comment]
We rarely delete specs. So don't count on it in the future. We don't currently have a process for deleting specs from trunk. If you'd like it removed there you can submit an issue on the trunk repo.

**Comment by King-Wizard** [comment]
Ok, done.

**Pull request merged**
