### PR TITLE
Remove FHSTwitterEngine 2.0.0

### PR DESCRIPTION
**Pull request by dkhamsing**
`2.0.0` was created before trunk service.. it was not pushed by owner

@segiddins mentioned that a proper `2.0.0` will not be possible after removal.. I think that is ok

### CODE REVIEW

**Comment by segiddins** [comment]
@keith ?

**Comment by keith** [comment]
It looks like people actually depend on this pod. There have been 445 installs in the past week. We should probably leave this one here.

**Comment by dkhamsing** [comment]
Is there a graceful way to let them go on `1.8.1` etc ?

**Comment by dkhamsing** [comment]
.. or.. what happens if I create a `2.0.1` ?

**Comment by dkhamsing** [comment]
@keith @segiddins will pushing a `2.0.1` be a workaround?

**Comment by dkhamsing** [comment]
Pushed 2.0.1, closing this. Thanks.

**Pull request closed without merging**
