### PR TITLE
Remove wrong version of SS-DomobAdSDK

### PR DESCRIPTION
**Pull request by shingwasix**
Podspec.json of version 4.4.8 contain a error.
4.4.8a & 4.4.8-1 are same as 4.4.8,so I want to remove them.

### CODE REVIEW

**Comment by shingwasix** [comment]
Is anybody here? (´･_･`)

**Comment by Keithbsmiley** [comment]
We have just launched 'Trunk', which is the new way for you to submit your Pods. For more information on this have a read through the post at http://blog.cocoapods.org/CocoaPods-Trunk/ If you have previously had your Pod merged into the master repository, please ensure you claim your Pod http://blog.cocoapods.org/Claim-Your-Pods/

**Comment by Keithbsmiley** [comment]
Also your spec is in ruby and has a JSON file extension. You'll need to fix that before you push it.

**Comment by Keithbsmiley** [comment]
You don't want to remove old versions of specs since this will break existing users projects.

**Comment by shingwasix** [comment]
But...the source codes of version  `4.4.8` & `4.4.8a` & `4.4.8-1` are same,I don't think users need `4.4.8a` & `4.4.8-1`.Existing users projects can using version `4.4.8` instead of `4.4.8a` & `4.4.8-1`.

**Pull request merged**
