### PR TITLE
Switch to working mirrors for OpenCV

### PR DESCRIPTION
**Pull request by kjkjava**
It looks like the current URLs for OpenCV [have been broken for over a month now](http://stackoverflow.com/questions/31005022/cant-install-opencv-with-cocoapods-could-not-resolve-host-hivelocity-dl-sourc). I updated the Podspec to a different SourceForge mirror for versions 2.4.9 and 2.4.10.

I also have a Podspec for OpenCV 3.0.0, but I assume I need to leave that up to the owner.

Thanks!

### CODE REVIEW

**Comment by kjkjava** [comment]
Also, it looks like 2.4.9.1 and 2.4.9.2 are the same as 2.4.9. I didn't mess with them.

**Comment by dholdren** [comment]
:+1:

**Comment by kylef** [comment]
I think it would be better to use a download link directly for sourceforge instead of a mirror. The direct link will redirect to an available mirror so it should prevent this problem from reoccurring when mirrors are changed.

```
https://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/3.0.0/opencv-3.0.0.zip
```

```shell
$ curl -I https://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/3.0.0/opencv-3.0.0.zip
HTTP/1.1 302 Found
Server: nginx
Date: Wed, 05 Aug 2015 12:21:12 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
content-disposition: attachment; filename="opencv-3.0.0.zip"
Set-Cookie: sf_mirror_attempt="opencvlibrary:netcologne:opencv-unix/3.0.0/opencv-3.0.0.zip"; expires=120; Path=/
Location: http://netcologne.dl.sourceforge.net/project/opencvlibrary/opencv-unix/3.0.0/opencv-3.0.0.zip
```

**Comment by kjkjava** [comment]
Good idea. I considered that but was unsure whether there was a good reason for using a specific mirror. Thanks and fixed.

**Pull request merged**
