### PR TITLE
Add OMPromises v0.4.0

### PR DESCRIPTION
**Pull request by aomader**

### CODE REVIEW

**Comment by keith** [comment]
#12199 (this was closed automatically, if your pull             request should not be closed based on that issue, please reopen it)

**Comment by b52** [comment]
Well, how do I claim my pod? I'm unable to push due to the following error: `[!] You are not allowed to push new versions for this pod.`

**Comment by keith** [comment]
You can do that here: https://trunk.cocoapods.org/claims/new

**Comment by b52** [comment]
@keith `Internal Server Error`

**Comment by keith** [comment]
Thanks for letting us know, it looks like the request still went through so you should be good to push now.

**Pull request closed without merging**
