### PR TITLE
Migrate specs that use the singular default_subspec to the plural def…

### PR DESCRIPTION
**Pull request by segiddins**
…ault_subspecs

@kylef you're changing adding the plural broke this about 20 months ago. Please review @keith.

---

Done with the following script:

``` ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
    gem 'cocoapods'
    gem 'json'
end

master = Pod::SourcesManager.master.first
pods = master.pods
pod_versions = pods.flat_map { |p| master.versions(p).map { |v| [p,v] }}
paths = pod_versions.map { |p, v| master.specification_path(p, v) }

paths.each do |path|
    contents = path.read
    next unless contents.gsub!(/default_subspec":\s*"(.*)"/, 'default_subspecs": ["\1"]')
    contents = JSON.pretty_generate(JSON.load(contents)) << "\n"
    path.open('w') { |f| f << contents }
end
```

### CODE REVIEW

**Comment by keith** [comment]
Seems good to me!

**Comment by kylef** [comment]
@segiddins The `default_subspecs` change was merged before these specs we're converted from Ruby to JSON :grimacing:, so technically my change did not break this, but the conversion to JSON specs did.

**Comment by kylef** [comment]
But :+1: on this change.

**Comment by keith** [comment]
@segiddins merge?

**Comment by segiddins** [comment]
Blarg there's a merge conflict. I'll recreate the change as soon as I can then merge straight away.

**Pull request merged**
