### PR TITLE
PodsTest0031

### PR DESCRIPTION
**Pull request by ShiYongjieGitHub**

### CODE REVIEW

**Comment by ShiYongjieGitHub** [comment]
Must i create the 'Pull Request' ？
If the request can't pass your review, the error '- ERROR | The `source_files` pattern did not match any file.' will show?
Can i just do this '$ pod trunk push PodsTest0031.podspec'?

**Comment by keith** [comment]
you shouldn't create a pull request. you'll have to fix that warning before pushing.

**Comment by ShiYongjieGitHub** [comment]
Could you please tell me how to fix the warning?

**Comment by keith** [comment]
Make sure that the `source_files` path is correct on all your specs.

**Comment by ShiYongjieGitHub** [comment]
Thanks a lot!

**Comment by ShiYongjieGitHub** [comment]
shiyongjieMac-mini:PodsTest003 shiyongjie$ pod lib lint

 -> PodsTest0031 (1.0.0)
    - ERROR | The `source_files` pattern did not match any file.

[!] PodsTest0031 did not pass validation.
You can use the `--no-clean` option to inspect any issue.
shiyongjieMac-mini:PodsTest003 shiyongjie$ pod lib lint

 -> PodsTest0031 (1.0.0)

PodsTest0031 passed validation.
shiyongjieMac-mini:PodsTest003 shiyongjie$ pod spec lint

 -> PodsTest0031 (1.0.0)
    - ERROR | The `source_files` pattern did not match any file.

Analyzed 1 podspec.

[!] The spec did not pass validation.

The 'pod lib lint ' command was successed, but why 'pod spec lint' failed?

**Comment by squarefrog** [comment]
The issue you have is your `source_files` pattern doesn't match anything. You use `AdrXMLToDictionaryParser.{h,m}` but your directory structure has `SYJXMLToDictionaryParser.{h,m}`.

Also **please** call your Pod something useful, like `SYJXMLToDictionaryParser` rather than `PodsTest0031`.

**Comment by ShiYongjieGitHub** [comment]
Ok ,thank you for the answer.

**Pull request closed without merging**
