### PR TITLE
Remove PLPlayerKit.

### PR DESCRIPTION
**Pull request by Phunk87**
PLPlayerKit is deprecated.

### CODE REVIEW

**Comment by squarefrog** [comment]
This is a bad user experience. There may be people using this pod and the next time they update or install they will get an error.

By far the best way to do this is to use the `deprecated_in_favor_of` tag. This at least warns the user the pod has been deprecated and offers an alternative.

**Comment by 0dayZh** [comment]
I know the deprecated_in_favor_of tag is almost the best practice. But this pod is special for our team. This Pod is built for our team private testing. After we test everything is ok, we wanna publish a pod for our customers that starts from version 1.0.0 and we are sure there still no one using it. So I send this request to ask a remove operation.

I figured out that there is a way to build a private pod, next time I will try it.

Thanks. This is important for us. 
Best wishes.

**Comment by 0dayZh** [comment]
The version I'm going to publish still named PLPlayerKit, so when i push it, i got an error:
```
[!] Unable to accept duplicate entry for: PLPlayerKit (1.0.0)
```
Is there anything else i should do to clean the deprecated version?

**Comment by Keithbsmiley** [comment]
Oh man this is a mess. You're trying to replace a spec with the same name with a new source? This is even worse than just removing a spec in the first place, since if anyone is trying to use this it will still work but it will download an entirely different codebase. I guess you can submit a PR for your new library but this is horrible. If you want to be able to use trunk you'll need to bump your version numbers.

**Comment by 0dayZh** [comment]
I see. Maybe rename is another way for me, thanks.

**Comment by Keithbsmiley** [comment]
Since the previous library was deleted, this might be less of an issue, since the specs obviously haven't worked since whenever that happened. I think changing the library name is probably a bad idea. I suppose submitting a PR for the new updates.

**Comment by 0dayZh** [comment]
So if I create a higher version with the same name via trunk, what will happen?

**Comment by 0dayZh** [comment]
@Keithbsmiley I used trunk to push a higher version pod, it works. I think I will never try to remove a spec again.

**Comment by Keithbsmiley** [comment]
:+1:

**Pull request merged**
