### PR TITLE
新增RqbHelper库

### PR DESCRIPTION
**Pull request by Renqianbei**
I have write a fileHelper to added to the pods

### CODE REVIEW

**Comment by 9527001** [comment]
问个问题 提交到cocoapod的库 如何才算是通过了 我qq号1508574114 谢谢

**Comment by 9527001** [comment]
我提交了5天了

**Comment by Renqianbei** [comment]
。。去自己github上的Fork 的仓库点newPullRequest 看记录

**Comment by STjason** [comment]
現在已經不用 pull request的方式了, 改用trunk push
參考這篇文獻中...
http://yulingtianxia.com/blog/2014/05/26/publish-your-pods-on-cocoapods-with-trunk/

**Comment by orta** [comment]
Back in early 2014 we [launched CocoaPods Trunk](http://blog.cocoapods.org/CocoaPods-Trunk/). Trunk is the only way that you can submit pods to CocoaPods, we do not accept pull requests to the CocoaPods Specs repo, and so this is being auto-closed. Please see #12199 for more info.

- To push a new version to trunk, you can use `pod trunk push`.
- You cannot amend an existing pod, however you can delete and deprecate a pod. You need to be using CocoaPods 1.0 to have access to `pod trunk delete` and `pod trunk deprecate`. People may be relying on your pod version, so use these with caution.
- If you don't have permission to update a pod that you own, please [file a claim](http://blog.cocoapods.org/Claim-Your-Pods/) on trunk.

**Pull request closed without merging**
