### PR TITLE
[Remove] SynergyKIT-SDK-iOS

### PR DESCRIPTION
**Pull request by jcislinsky**
Hello,
our strategy of development had change and we created new SDK for general public. Now it's needed delete this pod and create new fresh one.

Thank you.
Synergykit Team

### CODE REVIEW

**Comment by squarefrog** [comment]
This is strongly discouraged because if you do this it will break any user's projects which are using your specs. You could add your new versions via [Trunk](http://blog.cocoapods.org/CocoaPods-Trunk/) and mark the old ones as [`deprecated_in_favor_of`](http://guides.cocoapods.org/syntax/podspec.html#deprecated_in_favor_of) the new ones. This would probably be preferred.

**Comment by jcislinsky** [comment]
We know that and still need to delete it. This pod is used only in our company for internal projects.

**Comment by squarefrog** [comment]
OK. If your Pod is private, you may want to look at [Private Pods](http://guides.cocoapods.org/making/private-cocoapods.html).

**Comment by jcislinsky** [comment]
I thought that pod page on cocoapods.org will be deleted to. How can I delete this page https://cocoapods.org/pods/SynergyKIT-SDK-iOS ? Respectively, how can I create a new pod (clean) with the same name?

**Comment by squarefrog** [comment]
So if you ever intend to push a new version, then it is NOT recommended to delete. Deleted Pods have to manually be marked as deleted by a team member, which will also mean you cannot push a new version of the same podspec name.

In this case I recommend we revert this change, and you push a new version of your Pod with a higher version number. See https://github.com/CocoaPods/Specs/pull/13073#issuecomment-95937506

**Comment by jcislinsky** [comment]
But there are two problems. Repository have been moved to a new Organization and name of the product changed – only in case SynergyKIT —› Synergykit. How to do that?

And old versions of pod need to be deleted.

Thank you very much.

**Comment by jcislinsky** [comment]
What happens when we delete source repository of this pod? Will be pod page hidden and couldn't be searchable on cocoapods.com? How to remove pod from search? Thanks

**Comment by squarefrog** [comment]
To clarify, this pull request removed the Pod from the Specs repository. However, the Pod data also exists in the CocoaPods database - which enables searching through the API.

We only remove Pods in special cases.  The better experience for this would have been to mark the previous Pods as `deprecated_in_favor_of = 'SynergyKit-SDK'`. This efficiently informs any searchers to not use that pod and instead use the new one.

If you are happy with this I can revert this change and you can submit a new Pull Request after marking the previous Pods as [`deprecated_in_favor_of`](http://guides.cocoapods.org/syntax/podspec.html#deprecated_in_favor_of).

**Comment by jcislinsky** [comment]
Ok, thanks for your reply. I think this is special case. We already created new pod with rebranded name and new repository and old repository was deleted.

It would be really good if the old pod will be hidden from search: https://cocoapods.org/?q=synergykit . Is it possible?

**Comment by jcislinsky** [comment]
Is there any progress?

**Comment by squarefrog** [comment]
So just to clarify. Once the old Pod is marked as deleted, you will never be able to push to that name again.

Can you confirm exactly which of [these Pods](https://cocoapods.org/?q=synergykit) is the old one and must be deleted?

**Comment by jcislinsky** [comment]
The old one is "SynergyKIT-SDK-iOS". If it will be marked as deleted it disappear from search?

**Comment by squarefrog** [comment]
Yes it will

**Comment by jcislinsky** [comment]
Great, do it please.

**Pull request merged**
