### PR TITLE
these version are  useless

### PR DESCRIPTION
**Pull request by huangminlinux**

### CODE REVIEW

**Comment by keith** [comment]
Why are these "useless" ?

**Comment by huangminlinux** [comment]
because I make a mistake ,so the version 1.0.2 and version 1.0.3 is not work, and I want to delete these version and try again.

**Comment by keith** [comment]
You cannot submit the same version numbers again if we remove these. If you'd like you can submit a PR to fix these specific specs.

**Comment by huangminlinux** [comment]
i get it ,thx

**Comment by huangminlinux** [comment]
There is another problem bothering me。
I modify my source_files in my github repo for modify my pods ,but I fail . because I use ‘’pod install‘’ ，nothing updated
Are there a web server to storage my github repo，and how do I update it ？

**Comment by keith** [comment]
To update the source files you have to submit a pull request to this repo.

**Comment by huangminlinux** [comment]
all I need is modify the .podspec.json？   because there are only this file。
And I don't know its internal implementation。will you update the your storage according to my .podspec.json？

**Comment by keith** [comment]
Yes you'd need to up the json. You can reconvert your ruby spec from the command line. See `pod ipc --help` for info

**Pull request closed without merging**
