### PR TITLE
Remove temporary version of Segment Integrations

### PR DESCRIPTION
**Pull request by f2prateek**
The pods here were published as alpha releases to be able to test them out. We're switching to a different versioning scheme, and starting from 1.0.0 instead.

The only reason to delete these is so that they don't show up as the latest in the search results and confuse consumers.

https://cloudup.com/cMgUoJb-44F

I'm unsure if we'd have to delete these from CocoaPods trunk as well.

### CODE REVIEW

**Comment by f2prateek** [comment]
It seems that I would have to delete these from trunk since that's what the website uses. Is there a clear path for this? I see few relevant work (e.g https://github.com/CocoaPods/trunk.cocoapods.org/pull/144/files) but unsure if there is anything available currently.

**Comment by f2prateek** [comment]
if it's easier, we can delete these podspecs from here and trunk entirely (instead of just these specific versions) and I can republish the correct releases.

**Comment by orta** [comment]
Currently we've been slowly building out the ability to delete pods, but it's a work in progress. I've poked some people about it.

The only tool we currently have in our disposal makes them unusable in the future which is probably something you don't want. For now I'd recommend pushing a new version with a `deprecated_in_favor_of` flag that points to `Analytics`. Given that these are all alpha releases, CocoaPods would resolve to `1.0.0` instead of `7.2.0-alpha` without someone specifically stating the version.

**Comment by f2prateek** [comment]
> For now I'd recommend pushing a new version with a `deprecated_in_favor_of` flag that points to Analytics

Could you clarify what you mean by that? From what I can tell, I only deprecate the pod entirely, not a specific version.

e.g. I released a pod "Segment-Mixpanel" with the version [`2.9.0-alpha`](https://github.com/CocoaPods/Specs/tree/master/Specs/Segment-Mixpanel/2.9.0-alpha). I've released a stable version [`1.0.0`](https://github.com/CocoaPods/Specs/blob/master/Specs/Segment-Mixpanel/1.0.0/Segment-Mixpanel.podspec.json). I want to deprecate/delete the "2.9.0-alpha" release so that the latest version on the website is shown as "1.0.0" and not "2.9.0-alpha" (https://cocoapods.org/pods/Segment-Mixpanel). 

You're right in that the normal dependency resolution picks up `1.0.0` of "Segment-Mixpanel", but the website shows [`2.9.0-alpha`](https://cloudup.com/c38cdmr7C_R). Maybe I should raise in the `cocoadocs.org` repo? CocoaDocs does seem to do the expected thing and redirect http://cocoadocs.org/docsets/Segment-Mixpanel/ to `1.0.0`.

**Comment by floere** [comment]
@f2prateek Hi Prateek – would you mind reraising this in a short issue (referencing this one) on the search engine repo (that drives results on cocoapods.org)? -> https://github.com/CocoaPods/search.cocoapods.org
It appears your case is that you only have `-alpha` version pods and you'd like to switch to release versions. But you'd like the search results to then show the release version, right? (You are basically writing this in the first entry – just double checking if that's still where you are at)

**Comment by f2prateek** [comment]
Done! I think we can close this issue, since the pods don't really need to be deleted if the website will be able to show the latest stable release.

**Comment by floere** [comment]
@f2prateek I agree. For now I'll close this.

**Pull request closed without merging**
