### PR TITLE
TSMessages dependency of HexColors is needed in old Version

### PR DESCRIPTION
**Pull request by mRs-**
Hi im the author of HexColors and I fucked TSMessages up. In TSMessages the dependency is only set on HexColors regardless of the Version. 
In the newest version I changed the name of the classes from HexColor to HexColors.

To fix this issue i fixed the dependencies on the old files and now I'm only waiting for https://github.com/KrauseFx/TSMessages to tag the current Version on the master.

I handed in the newest version of TSMessages too (0.9.13)

### CODE REVIEW

**Comment by keith** [comment]
You'll need to submit the new version of this spec through trunk. Once you remove that from this PR we can merge this

**Comment by mRs-** [comment]
i removed the new version. just fixing the old ones :)

**Comment by keith** [comment]
Need a quick sign off from @KrauseFx

**Comment by KrauseFx** [comment]
@keith :+1:

**Pull request merged**
