### PR TITLE
Improve the performance of the index script

### PR DESCRIPTION
**Pull request by amorde**
Pulled from #14454

### CODE REVIEW

**Comment by amorde** [comment]
Netlify failed again, will have to take a look this weekend https://app.netlify.com/teams/cocoapods/builds/5ec5a333c3260c000651ab9a

```
2:41:52 PM: /opt/build/cache/bundle/ruby/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:208:in `specification_path': Unable to find the specification Spark-SDK (0.1.0) in the repo source. (Pod::StandardError)
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
2:41:52 PM: 	from Scripts/create_pods_and_versions_index.rb:59:in `block (3 levels) in <main>'
2:41:52 PM: 	from Scripts/create_pods_and_versions_index.rb:59:in `map'
2:41:52 PM: 	from Scripts/create_pods_and_versions_index.rb:59:in `block (2 levels) in <main>'
2:41:52 PM: 	from Scripts/create_pods_and_versions_index.rb:58:in `map'
2:41:52 PM: 	from Scripts/create_pods_and_versions_index.rb:58:in `block in <main>'
2:41:52 PM: 	from /opt/build/repo/Scripts/script_helper.rb:14:in `block in parallel_map'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:504:in `call_with_index'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:471:in `process_incoming_jobs'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:453:in `block in worker'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:444:in `fork'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:444:in `worker'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:435:in `block in create_workers'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `each'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `each_with_index'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:434:in `create_workers'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:373:in `work_in_processes'
2:41:52 PM: 	from /opt/build/cache/bundle/ruby/2.6.0/gems/parallel-1.17.0/lib/parallel.rb:277:in `map'
2:41:52 PM: 	from /opt/build/repo/Scripts/script_helper.rb:14:in `parallel_map'
2:41:52 PM: 	from Scripts/create_pods_and_versions_index.rb:57:in `<main>'
```

**Review by dnkoutso — APPROVED** [review]

**Comment by amorde** [comment]
At least what its failing on in fact does not exist https://github.com/CocoaPods/Specs/tree/master/Specs/d/3/5/Spark-SDK

Cant repro locally so still digging into why its failing only on Netlify

**Comment by amorde** [comment]
Ah, figured it out, is a case-sensitivity issue. the podspec was named with the name in lower case

https://github.com/CocoaPods/Specs/blob/master/Specs/d/3/5/Spark-SDK/0.1.0/spark-sdk.podspec.json

**Comment by amorde** [comment]
Welp, I fixed Netlify builds and ran it a couple times to make sure it had a cache hit, but its much slower on Netlify and slightly slower than our existing solution. Bummer.

Closing for now but will revisit if I come up with something that translates to Netlify well

**Pull request closed without merging**
