### PR TITLE
[Update] LibComponentLogging-pods 0.0.1, 0.0.2, 0.0.3

### PR DESCRIPTION
**Pull request by aharren**
fixes for https://github.com/CocoaPods/CocoaPods/issues/3997, and an update of lcl_configure for changed paths in CocoaPods 0.38.x

### CODE REVIEW

**Comment by keith** [comment]
You'll have to push the new version with trunk. But after you remove that from this I'll merge this.

**Comment by aharren** [comment]
LibComponentLogging specs don't work with trunk, because the Podfile which is used for validation is incomplete:

    $ pod trunk push 0.0.3

    [!] Found podspec `0.0.3/LibComponentLogging-pods.podspec.json`
    Updating spec repo `master`
    Validating podspec
     -> LibComponentLogging-pods (0.0.3)
        - WARN  | Unable to find a license file
        - ERROR | Returned an unsuccessful exit code. You can use `--verbose` for more information.
        - NOTE  |  LibComponentLogging-Core/lcl.h:156:13: fatal error: 'lcl_config_components.h' file not found

This is a long known issue. Please merge this request.

**Comment by aharren** [comment]
https://github.com/CocoaPods/Specs/pull/12835: "you will need to continue using pull-requests until we find a long-term solution for this problem."

**Comment by aharren** [comment]
Thx!

**Pull request merged**
