### PR TITLE
add ReactiveCocoa 2.4.5-2.4.7

### PR DESCRIPTION
**Pull request by chipp**

### CODE REVIEW

**Comment by Keithbsmiley** [comment]
We have just launched 'Trunk', which is the new way for you to submit your Pods. For more information on this have a read through the post at http://blog.cocoapods.org/CocoaPods-Trunk/ If you have previously had your Pod merged into the master repository, please ensure you claim your Pod http://blog.cocoapods.org/Claim-Your-Pods/

**Comment by ashfurrow** [comment]
I've cloned @chipp's branch locally and will `lint`/`trunk push` them.

**Comment by ashfurrow** [comment]
OK, I've pushed these in https://github.com/CocoaPods/Specs/commit/83f38b6364bf1b7022697d08dcf4faf23c923350 , https://github.com/CocoaPods/Specs/commit/6295b03b3300bf858681e85e05e09e7e38bb7589 , and https://github.com/CocoaPods/Specs/commit/4fd0e6ecb42d4b82597695b4368557cb39858e5d . Let me know if you have any problems, @chipp.

**Comment by chipp** [comment]
Thank you, @ashfurrow!
`Installing ReactiveCocoa 2.4.7 (was 2.4.4)`

**Pull request closed without merging**
