### PR TITLE
deprecate DeepLinkSDK in favor of DeepLinkKit

### PR DESCRIPTION
**Pull request by wessmith**
@segiddins I believe you and @chrismaddern spoke about this approach :smile:

### CODE REVIEW

**Comment by segiddins** [comment]
No need for the `deprecated: true` bit

**Comment by wessmith** [comment]
Ah, so I should remove it?

**Comment by segiddins** [comment]
Yeah, just the `deprecated_in_favor_of` is enough!

**Comment by keith** [comment]
Yes please

**Comment by wessmith** [comment]
@segiddins should be good now. Thanks!

**Comment by orta** [comment]
:+1:

**Pull request merged**
