### PR TITLE
Add LCProgressHUD&LCDownloadManager&LCActionSheet&LCNewFeature podspec file

### PR DESCRIPTION
**Pull request by iTofu**
Add LCProgressHUD&LCDownloadManager&LCActionSheet&LCNewFeature podspec file

### CODE REVIEW

**Comment by keith** [comment]
https://github.com/CocoaPods/Specs/pull/12199

**Comment by LeoiOS** [comment]
I can't search my repositories with "pod search <repositories  name>", e?

**Comment by keith** [comment]
See the linked issue. This was closed, not merged.

**Comment by LeoiOS** [comment]
Ok, ths.

**Pull request closed without merging**
