### PR TITLE
updating boost

### PR DESCRIPTION
**Pull request by StakshiGarg**

### CODE REVIEW

**Comment by squarefrog** [comment]
We have just launched 'Trunk', which is the new way for you to submit your Pods. For more information on this have a read through the post at http://blog.cocoapods.org/CocoaPods-Trunk/ If you have previously had your Pod merged into the master repository, please ensure you claim your Pod http://blog.cocoapods.org/Claim-Your-Pods/

**Comment by StakshiGarg** [comment]
pod trunk push Specs/boost/1.57.0/

[!] Found podspec `Specs/boost/1.57.0/boost.podspec.json`
Validating podspec
 -> boost (1.57.0)

[!] You are not allowed to push new versions for this pod.

getting this message when i tried to use trunk

**Comment by squarefrog** [comment]
That means you're not added as an author on that pod. Have a chat with @jcollas about this.

**Comment by StakshiGarg** [comment]
Thanks Paul. I have mailed him regarding the issue.

Best Regards
Stakshi

**Pull request closed without merging**
