### PR TITLE
Use jsDelivr for redirects

### PR DESCRIPTION
**Pull request by igor-makarov**
@dnkoutso please reopen before it goes stale 😂

### CODE REVIEW

**Comment by igor-makarov** [comment]
@dnkoutso This can go in regardless of Typhoeus status as it's indifferent to client impl.

**Review by amorde — APPROVED** [review]
This should significantly reduce the strain on Github placed by our Spec repo

**Comment by dnkoutso** [comment]
Lets do it!

**Comment by igor-makarov** [comment]
Wait, this is an old PR... They have a problem with us using it like this...

**Comment by igor-makarov** [comment]
Closed this. Long story - they have a problem with us using jsDelivr as a naked proxy to GH, because of performance. They can make a separate url but unfortunately they are only willing to give 1 week TTLs on json files, which would cause consistency issues.

Let's stick with GitHub CDN and assume that MSFT can handle the bill.

**Pull request closed without merging**
