### PR TITLE
Update Helpshift podspecs

### PR DESCRIPTION
**Pull request by rhishikeshj**
Since pod trunk push cant update an existing podspec, opening a pull request to merge the updated podpsec for version 5.5.0 and 5.5.1

### CODE REVIEW

**Comment by keith** [comment]
We have just launched 'Trunk', which is the new way for you to submit your Pods. For more information on this have a read through the post at http://blog.cocoapods.org/CocoaPods-Trunk/ If you have previously had your Pod merged into the master repository, please ensure you claim your Pod http://blog.cocoapods.org/Claim-Your-Pods/ #12199 (this was closed automatically, if your pull request should not be closed based on that issue, please reopen it)

**Comment by rhishikeshj** [comment]
I have already written my reason for opening this pull request. Please reopen and merge as appropriate

**Comment by rhishikeshj** [comment]
Your comment says that I should reopen the pull request but I dont see any way to do that other than to create a new one. Please advise asap. This is a high priority business issue for us. We have just pushed out an incorrect podspec and we wish to correct it soon.

**Comment by keith** [comment]
Instead of pushing an existing version you should push a new version. Also this diff includes way more than just the two versions you mentioned.

**Comment by rhishikeshj** [comment]
We track our podspec versions according to the native SDK versions that we have released. We cannot update a version when we are not updating the native SDK version. It becomes impossible to keep track of. Diff includes more than the 2 commits because we have not merged our fork with the Cocoapods master spec since the trunk system started.
What do you suggest I do if I want to update an existing version ?

**Comment by keith** [comment]
If you just need minor updates you can open a PR with only the two minor updates. Make sure not to include the number of commits you have here.

**Pull request closed without merging**
