### PR TITLE
remove my old spec

### PR DESCRIPTION
**Pull request by uxyheaven**

### CODE REVIEW

**Comment by uxyheaven** [comment]
XYQuickDeveloper is too old.
Now it is XYQuick.

**Comment by segiddins** [comment]
We'd prefer you deprecate the pod, instead of removing it which would break all of your user's CocoaPods setups.

**Comment by uxyheaven** [comment]
how to deprecate it？


发自 网易邮箱大师
在2015年12月11日 00:36，Samuel E. Giddins 写道:

We'd prefer you deprecate the pod, instead of removing it which would break all of your user's CocoaPods setups.

**Comment by segiddins** [comment]
Add `"deprecated_in_favor_of": "XYQuick"`

**Comment by keith** [comment]
Closing. You can submit a new PR with the deprecated attribute.

**Pull request closed without merging**
