### PR TITLE
Update SARate.podspec.json

### PR DESCRIPTION
**Pull request by GersonSilvaFilho**
Updated podspec to new version of iRate.

### CODE REVIEW

**Comment by keith** [comment]
We'll have to have @nicklockwood update this.

**Comment by keith** [comment]
@andrei200287 will need to take a look at this

**Comment by orta** [comment]
I've just emailed him about this PR

**Comment by andrei200287** [comment]
https://github.com/CocoaPods/Specs/commit/d3c50534a7d295cbc2335f2d8ffa6e22532d4ce9

**Comment by orta** [comment]
Awesome, thanks @andrei200287

**Pull request closed without merging**
