### PR TITLE
[Add] MPCoachMarks 0.0.3

### PR DESCRIPTION
**Pull request by bubudrc**
[Add] MPCoachMarks 0.0.3

### CODE REVIEW

**Comment by keith** [comment]
#12199 (this was closed automatically, if your pull             request should not be closed based on that issue, please reopen it)

**Comment by bubudrc** [comment]
I made all the steps... how can I reopen the pull request?

**Comment by keith** [comment]
Read the linked pull request to push your spec

**Comment by bubudrc** [comment]
I read the link and also made al the steps, bit it's closed. Why?

On . , July 13, 2015, Keith Smiley <notifications@github.com> wrote:

> Read the linked pull request to push your spec
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CocoaPods/Specs/pull/13300#issuecomment-120967506>.
>


-- 



*Marcelo Perretta*iOS Developer

MaWaPe Sistemas
Rosario. SF. Argentina
*Skype*: mwperretta
*Cel*.: +54 (341)3 774695

info@mawape.com

**Comment by keith** [comment]
Using pod trunk push negates the need for a pull request

**Comment by bubudrc** [comment]
I did por trunk push

On Monday, July 13, 2015, Keith Smiley <notifications@github.com> wrote:

> Using pod trunk push negates the need for a pull request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CocoaPods/Specs/pull/13300#issuecomment-120968486>.
>


-- 



*Marcelo Perretta*iOS Developer

MaWaPe Sistemas
Rosario. SF. Argentina
*Skype*: mwperretta
*Cel*.: +54 (341)3 774695

info@mawape.com

**Comment by keith** [comment]
So you don't need this.

**Pull request closed without merging**
