### PR TITLE
Add podspecs for Helpshift SDK version 5.5.1

### PR DESCRIPTION
**Pull request by rhishikeshj**
Since pod trunk push cant update an existing podspec, opening a pull request to merge the updated podpsec for version 5.5.0 and 5.5.1

### CODE REVIEW

**Comment by keith** [comment]
We have just launched 'Trunk', which is the new way for you to submit your Pods. For more information on this have a read through the post at http://blog.cocoapods.org/CocoaPods-Trunk/ If you have previously had your Pod merged into the master repository, please ensure you claim your Pod http://blog.cocoapods.org/Claim-Your-Pods/ #12199 (this was closed automatically, if your pull request should not be closed based on that issue, please reopen it)

**Comment by rhishikeshj** [comment]
Please reopen. This is according to the advice given here : https://github.com/CocoaPods/Specs/pull/13897

**Comment by orta** [comment]
These are not changes though, they're new files, you should be fine to push them through trunk? What am I missing here?

**Comment by rhishikeshj** [comment]
These are files that have already been committed to trunk via pod trunk push. But I could not see them in the master branch of Cocoapods-master. I only see json versions of the podspec. Is that what we should do ? Update the json pod spec files ?

**Comment by orta** [comment]
update the JSON versions, yes

**Pull request closed without merging**
