### PR TITLE
RealmSwift: Removed new line char "\n" from "version"

### PR DESCRIPTION
**Pull request by ugurcicekfidan**
New line char causes an error over NXRM. Removed new line "\n" from version.
CDN: *****-repository-cocoapods-proxy URL couldn't be downloaded: https://*******/repository/cocoapods-proxy/Specs/9/4/5/RealmSwift/0.92.1/RealmSwift.podspec.json Response: 500

javax.servlet.ServletException: java.lang.IllegalArgumentException: Illegal character in path at index 22: pods/RealmSwift/0.92.1
/https/api.github.com/repos/realm/realm-cocoa/tarball/v0.92.1.tar.gz

### CODE REVIEW

**Comment by lixiaoyu** [comment]
@ugurcicekfidan  hi ugurcicekfidan,have you solve the problem yet ?

**Comment by ugurcicekfidan** [comment]
@lixiaoyu not yet. Made a temporary solution by referencing them from github. If the problem solves, i will reference them from github to nexus.
**Podfile:**
`pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true`

**Comment by lixiaoyu** [comment]
oh thanks so much @ugurcicekfidan, but  it seems that if i reference **realm-cocoa** and **realm** from github,then repo **realm-cocoa** will not be cached in our nexus-cocoapod-repository. It may need to checkout every times we trigger a ci job . This two repo is too large which maybe our bottleneck in  "pod install" phase, it always take almost half hours sometimes. 

By the way,ugurcicekfidan, are you considering some other methods like hosted repository,  i read the nexus document, it only support **cocoapods-proxy**, but **cocoapods-hosted** not supported yet. Some other like npm or maven they supported.
image
Would you mind sharing some your best practise about this, thanks so much

**Comment by shithsnehasish** [comment]
Hi @ugurcicekfidan , I am also getting the above error while trying to download the dependency through nexus, "javax.servlet.ServletException: java.lang.IllegalArgumentException: Illegal character in path at index 22: pods/RealmSwift/0.93.1
/https/api.github.com/repos/realm/realm-cocoa/tarball/v0.93.1.tar.gz"

Please help!

**Pull request closed without merging**
