### PR TITLE
fix Spark-SDK pod name capitalization

### PR DESCRIPTION
**Pull request by idokleinman**

### CODE REVIEW

**Comment by Keithbsmiley** [comment]
I saw your [question on SO](http://stackoverflow.com/questions/28789807/how-to-rename-a-cocoapod) about this, I was reluctant to answer because it isn't clear to me what this will break. @orta may know more specifically, but I would worry about this affecting trunk, the filename case mismatch may break things as well.

**Comment by idokleinman** [comment]
Thanks Keith! this is a brand new pod I just published 3 days ago under wrong capitalisation, nothing will break

**Comment by orta** [comment]
As this is the first time this has been done, I'll keep an eye on it. I'm pretty comfortable with the change, I would recommend making a patch release sooner rather than later though, as that would ensure a lot of web things are 100%.

**Comment by idokleinman** [comment]
Thank you friends. Appreciate your support!

**Comment by Keithbsmiley** [comment]
I was not referring to things that would break for existing users but things that would break other CocoaPods services. Originally CocoaPods was completely case sensitive, so changing everything to be case-inesitive means there are some places where that can be weird. For example if you do `pod search Spark-SDK` this is the output:

```
-> spark-sdk (0.1.1)
   Spark mobile SDK for interacting with connected products via Spark Cloud
   pod 'spark-sdk', '~> 0.1.1'
   - Homepage: https://github.com/spark/spark-sdk-ios
   - Source:   https://github.com/spark/spark-sdk-ios.git
   - Versions: 0.1.1, 0.1.0 [master repo]
   - Sub specs:
     - Spark-SDK/Helpers (0.1.1)
     - Spark-SDK/SDK (0.1.1)
```

Luckily someone fixed this issue already but it's still pretty strange that you include the spec and subspecs with different casing.

**Comment by idokleinman** [comment]
I've fixed it to be all the same `Spark-SDK` now. 
thing is that when I try to do a `pod trunk push` I get:
```
[!] Found podspec `Spark-SDK.podspec`
Validating podspec
 -> Spark-SDK (0.1.2)

[!] The following validation failed:
- Name is already taken.
```

Now I am not really sure how to continue

**Comment by Keithbsmiley** [comment]
Right. This is because names are technically now case-insensitive. Which is for the better, but since you are having a case sensitivity issue it's a little annoying. To do this we would have to manually change it in the trunk database. This is why I would've rather not done this at all.

**Comment by idokleinman** [comment]
So in what way did the PR help? 
How should I proceed?

**Comment by Keithbsmiley** [comment]
Didn't really change anything. Everything that is still lowercase is either determined by the file path or the entry in trunk. Changing the case in git will break everyone's specs repo if I remember correctly. So you'd have to go down the rename path. Such as `SparkSDK`

**Comment by idokleinman** [comment]
Oh :(

**Comment by idokleinman** [comment]
changing back to lower case to continue development now things are breaking real bad 
```

[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 75d51309e1fc794f7e268a947e15585ba5152eb5
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.2
```

### Error

```
Errno::EEXIST - File exists - /private/tmp/CocoaPods/Lint/Pods/Target Support Files/Pods-spark-sdk
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/target_installer.rb:63:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/target_installer.rb:63:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/target_installer.rb:63:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:14:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:12:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:407:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:404:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:404:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:403:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:126:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:123:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:92:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:304:in `install_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:210:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:206:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:206:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:73:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/spec.rb:97:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/spec.rb:90:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/spec.rb:90:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.
```

**Comment by orta** [comment]
Try delete `/private/tmp/CocoaPods/Lint/Pods/Target Support Files/Pods-spark-sdk` and re-run - I think it's trying to clone locally into a folder that isn't being `rm`'d

**Comment by idokleinman** [comment]
good catch, all solved now, trunk is pushed, pod renamed. Many thanks!!

**Comment by orta** [comment]
:+1:

**Pull request merged**
