### PR TITLE
Gmail services included

### PR DESCRIPTION
**Pull request by chinnasamymca**
Need to include Gmail service in the Cocopods, For more details please contact chinnasamymca@yahoo.com

### CODE REVIEW

**Comment by Keithbsmiley** [comment]
Needs to be okayed by @Fl0p

**Comment by mrpatiwi** [comment]
I need this too

**Comment by Fl0p** [comment]
One moment

**Comment by Fl0p** [comment]
please use:

```
pod 'Google-API-Client', '~> 1.0.422'
```
It already with Gmail support

:closed_lock_with_key:

**Comment by chinnasamymca** [comment]
Thanks.

**Comment by Fl0p** [comment]
@Keithbsmiley 
close this

**Comment by chinnasamymca** [comment]
Done

**Pull request closed without merging**
